USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS STAGE_DB;
USE DATABASE STAGE_DB;
CREATE SCHEMA IF NOT EXISTS STAGE_SCHEMA;

-- Create an extra-small warehouse and will auto-suspend after 5 minutes of no use.

CREATE WAREHOUSE IF NOT EXISTS STAGE_WH WAREHOUSE_SIZE = XSMALL, MIN_CLUSTER_COUNT = 1, MAX_CLUSTER_COUNT = 2, SCALING_POLICY = ECONOMY, AUTO_SUSPEND = 5, INITIALLY_SUSPENDED = TRUE;